name: CIs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.type }}
  cancel-in-progress: true
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 4 * * 1"  # At 04:00 on Monday

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        mne: [main, maint/1.12]
        python: ['3.14']
        name: [PySide6]
        include:
          - os: ubuntu
            mne: main
            python: '3.11'
            qt: PyQt6
            name: PyQt6
          - os: ubuntu
            mne: maint/1.7  # 2 years back as of 2026/06/23
            python: '3.10'
            name: old
          - os: ubuntu
            mne: main
            python: '3.14'
            name: pip-pre
    name: pytest ${{ matrix.name }} / ${{ matrix.os }} / MNE ${{ matrix.mne }}
    runs-on: ${{ matrix.os }}-latest
    env:
      MNE_LOGGING_LEVEL: 'warning'
      OMP_NUM_THREADS: '1'
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          repository: mne-tools/mne-python
          path: mne-python
          ref: ${{ matrix.mne }}
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - run: |
          python -m pip install --upgrade pip
          test "$(git branch --show-current)" == "${{ matrix.mne }}"
          python -m pip install -e .
        name: Install MNE-Python
        working-directory: mne-python
      - name: Install
        run: python -m pip install -ve .[tests] "${{ matrix.qt || 'PySide6' }}"
      - name: Install pip-pre deps
        run: python -m pip install --upgrade --pre --only-binary ":all:" --default-timeout=60 --extra-index-url "https://pypi.anaconda.org/scientific-python-nightly-wheels/simple" "numpy>=2.6.0.dev0" "scipy>=1.19.0.dev0" "matplotlib>=3.12.0.dev0" "git+https://github.com/pyqtgraph/pyqtgraph.git"
        if: matrix.name == 'pip-pre'
      - run: ./tools/get_testing_version.sh
        working-directory: mne-python
      - uses: actions/cache@v6
        with:
          key: ${{ env.TESTING_VERSION }}
          path: ~/mne_data
      - run: python -c 'import mne; print(mne.datasets.testing.data_path(verbose=True))'
        name: 'Download testing data'
      - uses: pyvista/setup-headless-display-action@main
        with:
          qt: true
      - run: mne sys_info
      - run: pytest -m pgtest --cov=mne_qt_browser --cov-report=xml mne-python/mne/report mne-python/mne/viz
        name: Run MNE-Tests
      - run: pytest --error-for-skips tests/test_pg_specific.py --cov-report=xml --cov-append
        name: Run pyqtgraph-specific tests
      # These are slow on macOS, so skip them
      - run: pytest tests/test_speed.py --cov-report=xml --cov-append
        name: Run benchmarks
        if: runner.os != 'macOS'
      - uses: codecov/codecov-action@v7
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
